[SystemSettings]
; --- Post Processing ---
;r.FilmGrain=0
;r.Tonemapper.Quality=0
;r.DOF.Kernel.MaxBackgroundRadius=0
;r.DOF.Kernel.MaxForegroundRadius=0
;r.LightShaftBloomQuality=0
r.SceneColorFringeQuality=0
r.PostProcessing.QuarterResolutionDownsample=0
; --- Shadows ---
r.Shadow.RadiusThreshold=0
r.Shadow.MinResolution=1024
r.Shadow.MaxResolution=1024
r.Shadow.MaxCSMResolution=2048
r.Shadow.DistanceScale=0.85
r.Shadow.PreShadowResolutionFactor=1.0
r.Shadow.FarCascadesResolutionRatio=1.0
; --- Ambient Occlusion ---
r.DistanceFieldAO=1
r.AO.AllowLowNumConeSteps=0
r.AOQuality=1
r.AmbientOcclusion.DistanceCulling=1
r.AmbientOcclusionMaxQuality=100
r.SkylightIntensityMultiplier=1.0
; --- View Distance / LoD ---
r.StaticMeshLODDistanceScale=0.1
r.MaterialQualityLevel=1
r.ViewDistanceScale=5.0
foliage.LODDistanceScale=1.0
r.LightMaxDrawDistanceScale=1.0
wp.Runtime.GridLoadingRangeLevel=2
wp.Runtime.GridLoadingRangeScale=1.0
wp.Runtime.HLODLoadingRangeScale=1.0
; --- Streaming / Texture ---
r.MaxAnisotropy=16
r.Streaming.Boost=1.25
r.Streaming.UseAllMips=1
; --- Reflections / Others ---
r.Lumen.Reflections.SmoothBias=0.55
r.SSR.HalfResSceneColor=0
r.SSR.MaxRoughness=0.65
r.LightShaftDownSampleFactor=1
a.URO.ForceAnimRate=1
r.Upscale.Quality=3
r.UIRenderTargetQuality=100.0
r.Emitter.FastPoolEnable=1
r.EmitterSpawnRateScale=1.0
; --- Anti-aliasing ---
r.SMAA.Quality=3
r.SMAA.MaxSearchSteps=32
r.SMAA.MaxSearchStepsDiagonal=16
r.TemporalAA.Quality=3
r.TemporalAA.QualityForToon=3
r.TemporalAACurrentFrameWeight=0.25
r.TemporalAAFilterSize=0.1
r.TemporalAASamples=4
; --- NPC / Vehicle Density ---
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=1.25
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=1.05
UHTMassCrowdForceLODProcessor.MaxLODHighCount=5
UHTMassCrowdForceLODProcessor.MaxLODMediumCount=18
UHTMassCrowdForceLODProcessor.MaxLODLowCount=105
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=1.05
UHTMassVehicleForceLodProcessor.MaxLODHighCount=5
UHTMassVehicleForceLodProcessor.MaxLODMediumCount=10
UHTMassVehicleForceLodProcessor.MaxLODLowCount=95
HTAISpawnCache.DriveVehicleDensity=1.0

; --- UI Scale ---
[/Script/Engine.UserInterfaceSettings]
ApplicationScale=1.0

; --- Logging ---
[Core.Log]
global=none