; If you want SSR use Balanced Preset, you can adjust the individual settings after
; Extreme and Cinematic disables SSR even if you turn off Lumen

[ConsoleVariables]
r.PSOPrecaching=1
r.PSOPrecache.TranslucencyAllPass=1
; --- Post Processing ---
;r.FilmGrain=0
;r.BloomQuality=0
;r.Tonemapper.Quality=0
;r.DOF.Kernel.MaxBackgroundRadius=0
;r.DOF.Kernel.MaxForegroundRadius=0
;r.LightShaftBloomQuality=0
r.SceneColorFringeQuality=0
; --- Shadows ---
r.Shadow.RadiusThreshold=0
r.Shadow.MinResolution=1024
r.Shadow.MaxResolution=1024
r.Shadow.MaxCSMResolution=2048
r.Shadow.DistanceScale=0.85
r.Shadow.PreShadowResolutionFactor=1.0
r.Shadow.FarCascadesResolutionRatio=1.0
; --- Ambient Occlusion ---
r.DistanceFieldAO=1
r.AO.AllowLowNumConeSteps=1
r.AOQuality=1
r.AmbientOcclusion.DistanceCulling=1
r.AmbientOcclusionMaxQuality=100
r.SkylightIntensityMultiplier=1.0
; --- View Distance / LoD ---
r.StaticMeshLODDistanceScale=0.1
r.MaterialQualityLevel=1
r.ViewDistanceScale=3.0
foliage.LODDistanceScale=1.0
r.LightMaxDrawDistanceScale=1.0
wp.Runtime.GridLoadingRangeLevel=2
wp.Runtime.GridLoadingRangeScale=1.0
wp.Runtime.HLODLoadingRangeScale=1.0
; --- Streaming / Texture ---
r.MaxAnisotropy=16
r.Streaming.MinBoost=1.0
; --- Reflections / Others ---
r.Lumen.Reflections.SmoothBias=0.6
r.SSR.HalfResSceneColor=0
r.SSR.MaxRoughness=0.7
r.LightShaftDownSampleFactor=1
a.URO.ForceAnimRate=1
; --- Anti-aliasing ---
r.SMAA.Quality=3
r.SMAA.MaxSearchSteps=32
r.SMAA.MaxSearchStepsDiagonal=16
r.TemporalAA.Quality=3
r.TemporalAA.QualityForToon=3
r.TemporalAACurrentFrameWeight=0.35
r.TemporalAAFilterSize=0.1
r.TemporalAASamples=4
r.TSR.Velocity.WeightClampingSampleCount=1.0
r.TSR.ShadingRejection.Flickering.Period=0.05
r.TSR.Velocity.WeightClampingPixelSpeed=0.5
r.TSR.History.SampleCount=16
; --- NPC / Vehicle Density ---
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=1.5
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=1.2
HTMassCrowdSpawner.HTMassCrowdFixVisualCount=90
UHTMassCrowdForceLODProcessor.MaxLODHighCount=7
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=1.25
UHTMassVehicleForceLodProcessor.MaxLODHighCount=7
HTVisualNPCManager.VisualNormalNPCCount=20
HTAISpawnCache.DriveVehicleDensity=1.25

; --- UI Scale ---
[/Script/Engine.UserInterfaceSettings]
ApplicationScale=1.0

; --- Logging ---
[Core.Log]
global=none