; If you want SSR use Balanced Preset, you can adjust the individual settings after
; Extreme and Cinematic disables SSR even if you turn off Lumen

[ConsoleVariables]
r.PSOPrecaching=1
r.PSOPrecache.TranslucencyAllPass=1
; --- Post Processing ---
;r.FilmGrain=0
;r.BloomQuality=0
;r.Tonemapper.Quality=0
; --- Shadows ---
r.Shadow.RadiusThreshold=0.01
r.Shadow.MinResolution=1024
r.Shadow.MaxResolution=2048
r.Shadow.MaxCSMResolution=2048
; --- Ambient Occlusion ---
r.DistanceFieldAO=1
r.AO.AllowLowNumConeSteps=1
r.AOQuality=1
r.AmbientOcclusion.DistanceCulling=1
r.AmbientOcclusionMaxQuality=100
r.SkylightIntensityMultiplier=1.0
; --- View Distance / LoD ---
r.StaticMeshLODDistanceScale=0.5
r.MaterialQualityLevel=1
r.ViewDistanceScale=1.6
foliage.LODDistanceScale=2.0
r.LightMaxDrawDistanceScale=1.0
wp.Runtime.GridLoadingRangeLevel=2
wp.Runtime.GridLoadingRangeScale=1.0
wp.Runtime.HLODLoadingRangeScale=1.0
; --- Streaming / Texture ---
r.MaxAnisotropy=16
r.Streaming.MinBoost=1.5
; --- Reflections / Others ---
r.SSR.HalfResSceneColor=0
r.SSR.MaxRoughness=0.6
r.LightShaftDownSampleFactor=1
; --- Anti-aliasing ---
r.SMAA.Quality=3
r.SMAA.MaxSearchSteps=32
r.SMAA.MaxSearchStepsDiagonal=16
r.TemporalAA.Quality=3
r.TemporalAA.QualityForToon=3
r.TemporalAACurrentFrameWeight=0.35
r.TemporalAAFilterSize=0.1
r.TemporalAASamples=4
r.TSR.Velocity.WeightClampingSampleCount=1.0
r.TSR.ShadingRejection.Flickering.Period=0.05
r.TSR.Velocity.WeightClampingPixelSpeed=0.5
r.TSR.History.SampleCount=16
; --- NPC / Vehicle Density ---
MassParkedVehicleSpawner.MassParkedVehicleSpawnerScale=1.5
HTMassCrowdSpawner.HTMassCrowdSpawnerScale=1.5
HTMassCrowdSpawner.HTMassCrowdFixVisualCount=108
UHTMassCrowdForceLODProcessor.MaxLODHighCount=10
HTMassVehicleSpawner.HTMassVehicleSpawnerScale=2
UHTMassVehicleForceLodProcessor.MaxLODHighCount=10
HTVisualNPCManager.VisualNormalNPCCount=25
HTAISpawnCache.DefaultDensity=1.5
HTAISpawnCache.DriveVehicleDensity=2.0
; --- NVIDIA Reflex ---
t.Streamline.Reflex.HandleMaxTickRate=true
t.Streamline.Reflex.Enable=1
t.Streamline.Reflex.Mode=1

; --- UI Scale ---
[/Script/Engine.UserInterfaceSettings]
ApplicationScale=1.0