; If you need more FPS, use TAA and lower rendering accuracy to 0.8

[ConsoleVariables]
r.PSOPrecaching=1
r.PSOPrecache.TranslucencyAllPass=1
; --- Post Processing ---
;r.FilmGrain=0
;r.BloomQuality=0
;r.Tonemapper.Quality=0
;r.DOF.Kernel.MaxBackgroundRadius=0
;r.DOF.Kernel.MaxForegroundRadius=0
;r.LightShaftBloomQuality=0
r.SceneColorFringeQuality=0
; --- Shadows ---
r.Shadow.RadiusThreshold=0.04
r.Shadow.MinResolution=256
r.Shadow.MaxResolution=512
r.Shadow.MaxCSMResolution=512
r.Shadow.DistanceScale=0.6
r.Shadow.PreShadowResolutionFactor=0.5
r.Shadow.FarCascadesResolutionRatio=0.5
; --- Ambient Occlusion ---
r.DistanceFieldAO=0
r.AmbientOcclusionMaxQuality=0
; --- View Distance / LoD ---
r.StaticMeshLODDistanceScale=1.0
r.MaterialQualityLevel=0
r.ViewDistanceScale=0.8
foliage.LODDistanceScale=0.8
r.LightMaxDrawDistanceScale=0.5
wp.Runtime.GridLoadingRangeLevel=0
; Lower values for the two commands below if you need more FPS
wp.Runtime.GridLoadingRangeScale=0.6
wp.Runtime.HLODLoadingRangeScale=0.9
; --- Streaming / Texture ---
r.MaxAnisotropy=8
r.Streaming.MinBoost=1.0
; --- Reflections / Others ---
r.SSR.HalfResSceneColor=1
r.SSR.MaxRoughness=0.7
r.LightShaftDownSampleFactor=2
a.URO.ForceAnimRate=1
; --- Anti-aliasing ---
r.SMAA.Quality=3
r.SMAA.MaxSearchSteps=32
r.SMAA.MaxSearchStepsDiagonal=16
r.TemporalAA.Quality=3
r.TemporalAA.QualityForToon=3
r.TemporalAACurrentFrameWeight=0.35
r.TemporalAAFilterSize=0.1
r.TemporalAASamples=4
r.TemporalAA.Upsampling=1
r.TSR.Velocity.WeightClampingSampleCount=1.0
r.TSR.ShadingRejection.Flickering.Period=0.05
r.TSR.Velocity.WeightClampingPixelSpeed=0.5
r.TSR.History.SampleCount=16
; --- NVIDIA Reflex ---
t.Streamline.Reflex.HandleMaxTickRate=true
t.Streamline.Reflex.Enable=1
t.Streamline.Reflex.Mode=1

; --- UI Scale ---
[/Script/Engine.UserInterfaceSettings]
ApplicationScale=1.0

; --- Logging ---
[Core.Log]
global=none